/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on 16/08/2011, 09:21:51 AM
 */

package com.contab.view;

import com.contab.bean.BeanBanco;
import com.contab.bean.BeanEmpresa;
import com.contab.combobox.ComboModelCuentaBanco;
import com.contab.combobox.ComboModelEmpresas;
import com.contab.logic.LogicCuentaBanco;
import com.contab.logic.LogicEmpresa;


import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import org.openide.util.Exceptions;

/**
 *
 * @author user
 */
public class formCaja extends javax.swing.JPanel {

    /** Creates new form NewJPanel */

     private ComboModelEmpresas modelcbempresa = new ComboModelEmpresas(LogicEmpresa.listaDeEmpresa());
     private ComboModelCuentaBanco modelcbctabanco = new ComboModelCuentaBanco();
    public formCaja() throws SQLException {
        initComponents();
        asignar();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        empresa = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inicioFecha = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAno = new javax.swing.JTextPane();
        btnBanco = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbmov = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbImpresora = new javax.swing.JComboBox();

        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(formCaja.class, "formCaja.jLabel1.text_1_1")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(formCaja.class, "formCaja.jLabel2.text_1_1")); // NOI18N

        inicioFecha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "junio", "julio", "Agosto ", "Setiembre", "octubre", "Noviembre", "Diciembre" }));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(formCaja.class, "formCaja.jLabel3.text_1_1")); // NOI18N

        jScrollPane1.setViewportView(txtAno);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(formCaja.class, "formCaja.jLabel4.text_1_1")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(formCaja.class, "formCaja.jLabel5.text_2")); // NOI18N

        cbmov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Cuenta Corriente" }));
        cbmov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmovActionPerformed(evt);
            }
        });

        jLabel6.setText(org.openide.util.NbBundle.getMessage(formCaja.class, "formCaja.jLabel6.text")); // NOI18N

        cmbImpresora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Continuo", "Lasert" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbmov, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(empresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inicioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        // TODO add your handling code here:
       BeanEmpresa emp=((ComboModelEmpresas)empresa.getModel()).getElement(empresa.getSelectedIndex());
          int inicioM=this.cbmov.getSelectedIndex();
        try {
            if(inicioM==0){
            //    btnBanco.setEnabled(false);

            ArrayList<BeanBanco> array = LogicCuentaBanco.listaCuentaEfectivo(emp.getCodigo());
            modelcbctabanco.setData(array);
            btnBanco.setModel(modelcbctabanco);
            btnBanco.updateUI();
            }else{
             //   btnBanco.setEnabled(true);

             ArrayList<BeanBanco> array = LogicCuentaBanco.listaCuentaBanco(emp.getCodigo());
            modelcbctabanco.setData(array);
           btnBanco.setModel(modelcbctabanco);
           btnBanco.updateUI();
            }

        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }

        

       
    }//GEN-LAST:event_empresaActionPerformed

    private void cbmovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmovActionPerformed
        // TODO add your handling code here:
      //  btnBanco.disable();
         BeanEmpresa emp=((ComboModelEmpresas)empresa.getModel()).getElement(empresa.getSelectedIndex());
          int inicioM=this.cbmov.getSelectedIndex();
        try {
            if(inicioM==0){
            //    btnBanco.setEnabled(false);
              
            ArrayList<BeanBanco> array = LogicCuentaBanco.listaCuentaEfectivo(emp.getCodigo());
            modelcbctabanco.setData(array);
            btnBanco.setModel(modelcbctabanco);
            btnBanco.updateUI();
            }else{
             //   btnBanco.setEnabled(true);

             ArrayList<BeanBanco> array = LogicCuentaBanco.listaCuentaBanco(emp.getCodigo());
            modelcbctabanco.setData(array);
           btnBanco.setModel(modelcbctabanco);
           btnBanco.updateUI();
            }

        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }

    }//GEN-LAST:event_cbmovActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox btnBanco;
    private javax.swing.JComboBox cbmov;
    private javax.swing.JComboBox cmbImpresora;
    private javax.swing.JComboBox empresa;
    private javax.swing.JComboBox inicioFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtAno;
    // End of variables declaration//GEN-END:variables

     public void asignar() throws SQLException {
            empresa.setModel(modelcbempresa);

     }
    

    public JComboBox getEmpresa() {
        return empresa;
    }

    public JComboBox getCuentaBanco() {
        return btnBanco;
    }


    public JComboBox getInicioFecha() {
        return inicioFecha;
    }


    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public ComboModelEmpresas getModelcbempresa() {
        return modelcbempresa;
    }

    public JTextPane getTxtAno() {
        return txtAno;
    }

    public JComboBox getjComboBox1() {
        return cbmov;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JComboBox getBtnBanco() {
        return btnBanco;
    }

    /**
     * @return the cmbImpresora
     */
    public javax.swing.JComboBox getCmbImpresora() {
        return cmbImpresora;
    }

    /**
     * @param cmbImpresora the cmbImpresora to set
     */
    public void setCmbImpresora(javax.swing.JComboBox cmbImpresora) {
        this.cmbImpresora = cmbImpresora;
    }

    /**
     * @return the cmbImpresora
     */
 

}
