/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAnalisisCuentaAuxiliar.java
 *
 * Created on 23-jun-2012, 11:47:47
 */
package com.contab.view;

/**
 *
 * @author cixtic04
 */
public class FrmAnalisisCuentaAuxiliar extends javax.swing.JFrame {

    /** Creates new form FrmAnalisisCuentaAuxiliar */
    public FrmAnalisisCuentaAuxiliar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jtoolbmenu = new javax.swing.JToolBar();
        jbtnCerrar = new javax.swing.JButton();
        jbtnCerrar1 = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();
        jbtnAceptar1 = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jLabel12 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jXTable2 = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtoolbmenu.setBackground(new java.awt.Color(255, 255, 255));
        jtoolbmenu.setFloatable(false);
        jtoolbmenu.setAutoscrolls(true);
        jtoolbmenu.setBorderPainted(false);
        jtoolbmenu.setFocusTraversalPolicyProvider(true);
        jtoolbmenu.setInheritsPopupMenu(true);
        jtoolbmenu.setOpaque(false);

        jbtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\nuevo.png")); // NOI18N
        jbtnCerrar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jbtnCerrar.toolTipText")); // NOI18N
        jbtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnCerrar);

        jbtnCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar1.setIcon(new javax.swing.ImageIcon("E:\\sistema_ERP\\ERPSistemaContable\\src\\com\\gps\\erp\\vista\\images\\guardar.png")); // NOI18N
        jbtnCerrar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jbtnCerrar1.toolTipText")); // NOI18N
        jbtnCerrar1.setActionCommand(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jbtnCerrar1.actionCommand")); // NOI18N
        jbtnCerrar1.setFocusable(false);
        jbtnCerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnCerrar1);

        jbtnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnNuevo.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\buscar2.png")); // NOI18N
        jbtnNuevo.setToolTipText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jbtnNuevo.toolTipText")); // NOI18N
        jbtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnNuevo);

        jbtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\table-add-icon.png")); // NOI18N
        jbtnAceptar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jbtnAceptar.toolTipText")); // NOI18N
        jbtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnAceptar);

        jbtnAceptar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-delete-icon.png")); // NOI18N
        jbtnAceptar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jbtnAceptar1.toolTipText")); // NOI18N
        jbtnAceptar1.setFocusable(false);
        jbtnAceptar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnAceptar1);

        jbtnEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-excel-icon.png")); // NOI18N
        jbtnEditar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jbtnEditar.toolTipText")); // NOI18N
        jbtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnEditar);

        getContentPane().add(jtoolbmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField2.text")); // NOI18N
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.setFocusCycleRoot(true);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 70, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 160, -1));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel2.text")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextField3.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField3.text")); // NOI18N
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.setFocusCycleRoot(true);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 70, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 160, -1));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel3.text")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jTextField4.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField4.text")); // NOI18N
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField4.setFocusCycleRoot(true);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 160, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, -1));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel4.text")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTextField5.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField5.text")); // NOI18N
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField5.setFocusCycleRoot(true);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 70, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 200, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jPanel3.border.title"))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton1.text")); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton2.text")); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton3.text")); // NOI18N

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton4.text")); // NOI18N

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton5.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 160));

        jLabel6.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel6.text")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jTextField7.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField7.text")); // NOI18N
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField7.setFocusCycleRoot(true);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 70, -1));

        jLabel7.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel7.text")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jTextField8.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField8.text")); // NOI18N
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField8.setFocusCycleRoot(true);
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 70, -1));

        jLabel8.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel8.text")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jTextField9.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField9.text")); // NOI18N
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField9.setFocusCycleRoot(true);
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 70, -1));

        jLabel9.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel9.text")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        jTextField10.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField10.text")); // NOI18N
        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField10.setFocusCycleRoot(true);
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 70, -1));

        jLabel10.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel10.text")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jTextField11.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField11.text")); // NOI18N
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField11.setFocusCycleRoot(true);
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 70, -1));

        jCheckBox1.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jCheckBox1.text")); // NOI18N
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jCheckBox2.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jCheckBox2.text")); // NOI18N
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jPanel4.border.title"))); // NOI18N

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton6.text")); // NOI18N

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton7.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton6)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton7)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 310, 80));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jPanel5.border.title"))); // NOI18N

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton8.text")); // NOI18N

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton9.text")); // NOI18N

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton10.text")); // NOI18N

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jRadioButton11.text")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 310, 100));

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jPanel6.border.title"))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jScrollPane2.setViewportView(jXTable1);
        jXTable1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable1.columnModel.title0")); // NOI18N

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 730, 187));

        jLabel12.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel12.text")); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jTextField15.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField15.text")); // NOI18N
        jTextField15.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField15.setFocusCycleRoot(true);
        jPanel6.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 93, -1));

        jLabel11.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel11.text")); // NOI18N
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jTextField12.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField12.text")); // NOI18N
        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField12.setFocusCycleRoot(true);
        jPanel6.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 82, -1));

        jLabel13.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel13.text")); // NOI18N
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jTextField13.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField13.text")); // NOI18N
        jTextField13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField13.setFocusCycleRoot(true);
        jPanel6.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 93, -1));

        jLabel14.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jLabel14.text")); // NOI18N
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jTextField14.setText(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jTextField14.text")); // NOI18N
        jTextField14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField14.setFocusCycleRoot(true);
        jPanel6.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 93, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 755, 270));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jPanel7.border.title"))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "JrnNumber", "Journal type", "Débito Base", "Crédito Base", "Débito Exit", "Crédito Exit", "F.Movimiento", "Glosa", "Tipo Cambio"
            }
        ));
        jScrollPane3.setViewportView(jXTable2);
        jXTable2.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable2.columnModel.title0")); // NOI18N
        jXTable2.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable2.columnModel.title1")); // NOI18N
        jXTable2.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable2.columnModel.title2")); // NOI18N
        jXTable2.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable2.columnModel.title3")); // NOI18N
        jXTable2.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable2.columnModel.title4")); // NOI18N
        jXTable2.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable2.columnModel.title5")); // NOI18N
        jXTable2.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable2.columnModel.title6")); // NOI18N
        jXTable2.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable2.columnModel.title7")); // NOI18N
        jXTable2.getColumnModel().getColumn(8).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jXTable2.columnModel.title8")); // NOI18N

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, 738, 170));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 750, 210));

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(FrmAnalisisCuentaAuxiliar.class, "FrmAnalisisCuentaAuxiliar.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisisCuentaAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisisCuentaAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisisCuentaAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAnalisisCuentaAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmAnalisisCuentaAuxiliar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private org.jdesktop.swingx.JXTable jXTable1;
    private org.jdesktop.swingx.JXTable jXTable2;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnAceptar1;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JButton jbtnCerrar1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JToolBar jtoolbmenu;
    // End of variables declaration//GEN-END:variables
}
