/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmConsultaSaldoPorAuxiliar.java
 *
 * Created on 23-jun-2012, 11:00:45
 */
package com.contab.view;

/**
 *
 * @author cixtic04
 */
public class FrmConsultaSaldoPorAuxiliar extends javax.swing.JFrame {

    /** Creates new form FrmConsultaSaldoPorAuxiliar */
    public FrmConsultaSaldoPorAuxiliar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtoolbmenu = new javax.swing.JToolBar();
        jbtnCerrar = new javax.swing.JButton();
        jbtnCerrar1 = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();
        jbtnAceptar1 = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtoolbmenu.setBackground(new java.awt.Color(255, 255, 255));
        jtoolbmenu.setFloatable(false);
        jtoolbmenu.setAutoscrolls(true);
        jtoolbmenu.setBorderPainted(false);
        jtoolbmenu.setFocusTraversalPolicyProvider(true);
        jtoolbmenu.setInheritsPopupMenu(true);
        jtoolbmenu.setOpaque(false);

        jbtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\nuevo.png")); // NOI18N
        jbtnCerrar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jbtnCerrar.toolTipText")); // NOI18N
        jbtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnCerrar);

        jbtnCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar1.setIcon(new javax.swing.ImageIcon("E:\\sistema_ERP\\ERPSistemaContable\\src\\com\\gps\\erp\\vista\\images\\guardar.png")); // NOI18N
        jbtnCerrar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jbtnCerrar1.toolTipText")); // NOI18N
        jbtnCerrar1.setActionCommand(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jbtnCerrar1.actionCommand")); // NOI18N
        jbtnCerrar1.setFocusable(false);
        jbtnCerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnCerrar1);

        jbtnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnNuevo.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\buscar2.png")); // NOI18N
        jbtnNuevo.setToolTipText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jbtnNuevo.toolTipText")); // NOI18N
        jbtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnNuevo);

        jbtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\table-add-icon.png")); // NOI18N
        jbtnAceptar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jbtnAceptar.toolTipText")); // NOI18N
        jbtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnAceptar);

        jbtnAceptar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-delete-icon.png")); // NOI18N
        jbtnAceptar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jbtnAceptar1.toolTipText")); // NOI18N
        jbtnAceptar1.setFocusable(false);
        jbtnAceptar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnAceptar1);

        jbtnEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-excel-icon.png")); // NOI18N
        jbtnEditar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jbtnEditar.toolTipText")); // NOI18N
        jbtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnEditar);

        getContentPane().add(jtoolbmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jPanel2.border.title"))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jLabel1.text")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jTextField2.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jTextField2.text")); // NOI18N
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.setFocusCycleRoot(true);
        jTextField2.setNextFocusableComponent(jTextField3);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 160, -1));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jLabel2.text")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextField3.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jTextField3.text")); // NOI18N
        jTextField3.setFocusCycleRoot(true);
        jTextField3.setNextFocusableComponent(jTextField5);
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 160, -1));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jLabel3.text")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTextField4.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jTextField4.text")); // NOI18N
        jTextField4.setFocusCycleRoot(true);
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, -1));

        jTextField5.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jTextField5.text")); // NOI18N
        jTextField5.setFocusCycleRoot(true);
        jTextField5.setNextFocusableComponent(jTextField6);
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 70, -1));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jLabel4.text")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jTextField6.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jTextField6.text")); // NOI18N
        jTextField6.setFocusCycleRoot(true);
        jTextField6.setNextFocusableComponent(jTextField7);
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 70, -1));

        jTextField7.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jTextField7.text")); // NOI18N
        jTextField7.setFocusCycleRoot(true);
        jTextField7.setNextFocusableComponent(jTextField8);
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 70, -1));

        jLabel5.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jLabel5.text")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel6.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jLabel6.text")); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jTextField8.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jTextField8.text")); // NOI18N
        jTextField8.setFocusCycleRoot(true);
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 70, -1));

        jCheckBox1.setText(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jCheckBox1.text")); // NOI18N
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 720, 120));

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cuenta", "Centro", "Código Cuenta Auxiliar", "Cuenta Auxiliar", "Saldo Base Anterior", "Saldo Extranjero Anterior", "Saldo Base Actual", "Saldo Extranjero Actual"
            }
        ));
        jScrollPane1.setViewportView(jXTable1);
        jXTable1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jXTable1.columnModel.title0")); // NOI18N
        jXTable1.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jXTable1.columnModel.title1")); // NOI18N
        jXTable1.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jXTable1.columnModel.title2")); // NOI18N
        jXTable1.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jXTable1.columnModel.title7")); // NOI18N
        jXTable1.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jXTable1.columnModel.title3")); // NOI18N
        jXTable1.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jXTable1.columnModel.title4")); // NOI18N
        jXTable1.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jXTable1.columnModel.title5")); // NOI18N
        jXTable1.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmConsultaSaldoPorAuxiliar.class, "FrmConsultaSaldoPorAuxiliar.jXTable1.columnModel.title6")); // NOI18N

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 720, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaSaldoPorAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaSaldoPorAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaSaldoPorAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaSaldoPorAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmConsultaSaldoPorAuxiliar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnAceptar1;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JButton jbtnCerrar1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JToolBar jtoolbmenu;
    // End of variables declaration//GEN-END:variables
}
