/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmLibroMayor.java
 *
 * Created on 25-jun-2012, 9:43:14
 */
package com.contab.view;

/**
 *
 * @author cixtic04
 */
public class FrmLibroMayor extends javax.swing.JFrame {

    /** Creates new form FrmLibroMayor */
    public FrmLibroMayor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtoolbmenu = new javax.swing.JToolBar();
        jbtnCerrar = new javax.swing.JButton();
        jbtnCerrar1 = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();
        jbtnAceptar1 = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtoolbmenu.setBackground(new java.awt.Color(255, 255, 255));
        jtoolbmenu.setFloatable(false);
        jtoolbmenu.setAutoscrolls(true);
        jtoolbmenu.setBorderPainted(false);
        jtoolbmenu.setFocusTraversalPolicyProvider(true);
        jtoolbmenu.setInheritsPopupMenu(true);
        jtoolbmenu.setOpaque(false);

        jbtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\nuevo.png")); // NOI18N
        jbtnCerrar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jbtnCerrar.toolTipText")); // NOI18N
        jbtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnCerrar);

        jbtnCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar1.setIcon(new javax.swing.ImageIcon("E:\\sistema_ERP\\ERPSistemaContable\\src\\com\\gps\\erp\\vista\\images\\guardar.png")); // NOI18N
        jbtnCerrar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jbtnCerrar1.toolTipText")); // NOI18N
        jbtnCerrar1.setActionCommand(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jbtnCerrar1.actionCommand")); // NOI18N
        jbtnCerrar1.setFocusable(false);
        jbtnCerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnCerrar1);

        jbtnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnNuevo.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\buscar2.png")); // NOI18N
        jbtnNuevo.setToolTipText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jbtnNuevo.toolTipText")); // NOI18N
        jbtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnNuevo);

        jbtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\table-add-icon.png")); // NOI18N
        jbtnAceptar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jbtnAceptar.toolTipText")); // NOI18N
        jbtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnAceptar);

        jbtnAceptar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-delete-icon.png")); // NOI18N
        jbtnAceptar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jbtnAceptar1.toolTipText")); // NOI18N
        jbtnAceptar1.setFocusable(false);
        jbtnAceptar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnAceptar1);

        jbtnEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-excel-icon.png")); // NOI18N
        jbtnEditar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jbtnEditar.toolTipText")); // NOI18N
        jbtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnEditar);

        getContentPane().add(jtoolbmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jPanel2.border.title"))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jLabel1.text")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextField2.setText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTextField2.text")); // NOI18N
        jTextField2.setFocusCycleRoot(true);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 160, -1));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jLabel2.text")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jTextField3.setText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTextField3.text")); // NOI18N
        jTextField3.setFocusCycleRoot(true);
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 70, -1));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jLabel3.text")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, -1));

        jTextField4.setText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTextField4.text")); // NOI18N
        jTextField4.setFocusCycleRoot(true);
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 160, -1));

        jCheckBox1.setText(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jCheckBox1.text")); // NOI18N
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 730, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cuenta", "C.Costo", "Descrip. Cuenta", "Fecha", "Nro.Asiento", "Nro.Interno", "Nro.Externo", "Glosa", "Debito Base", "Crédito Base", "Debito ME", "Crédito ME"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title2")); // NOI18N
        jTable1.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title3")); // NOI18N
        jTable1.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title4")); // NOI18N
        jTable1.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title1_1")); // NOI18N
        jTable1.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title5")); // NOI18N
        jTable1.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title6")); // NOI18N
        jTable1.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title7")); // NOI18N
        jTable1.getColumnModel().getColumn(8).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title8")); // NOI18N
        jTable1.getColumnModel().getColumn(9).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title9")); // NOI18N
        jTable1.getColumnModel().getColumn(10).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title10")); // NOI18N
        jTable1.getColumnModel().getColumn(11).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title11")); // NOI18N

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 730, 210));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Contenidos", "Cta.Contable", "C.Costo", "Descripción", "Moneda"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title0")); // NOI18N
        jTable2.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title1")); // NOI18N
        jTable2.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title2")); // NOI18N
        jTable2.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title3")); // NOI18N
        jTable2.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmLibroMayor.class, "FrmLibroMayor.jTable1.columnModel.title4")); // NOI18N

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 730, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLibroMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLibroMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLibroMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLibroMayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmLibroMayor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnAceptar1;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JButton jbtnCerrar1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JToolBar jtoolbmenu;
    // End of variables declaration//GEN-END:variables
}
