/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmMantenimientoDeAsientoTipo1.java
 *
 * Created on 21-jun-2012, 17:09:16
 */
package com.contab.view;

/**
 *
 * @author cixtic04
 */
public class FrmMantenimientoDeAsientoTipo extends javax.swing.JFrame {

    /** Creates new form FrmMantenimientoDeAsientoTipo1 */
    public FrmMantenimientoDeAsientoTipo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jtoolbmenu = new javax.swing.JToolBar();
        jbtnCerrar1 = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnCerrar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jPanel2.border.title"))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jLabel1.text")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jLabel2.text")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jTextField2.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jTextField2.text")); // NOI18N
        jTextField2.setFocusCycleRoot(true);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, -1));

        jRadioButton1.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jRadioButton1.text")); // NOI18N
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 110, -1));

        jRadioButton3.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jRadioButton3.text")); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 110, -1));

        jRadioButton4.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jRadioButton4.text")); // NOI18N
        jPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 130, -1));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jLabel3.text")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jTextField3.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jTextField3.text")); // NOI18N
        jTextField3.setFocusCycleRoot(true);
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 70, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 160, -1));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jLabel4.text")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jTextField4.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jTextField4.text")); // NOI18N
        jTextField4.setFocusCycleRoot(true);
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, -1));

        jLabel5.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jLabel5.text")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jTextField5.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jTextField5.text")); // NOI18N
        jTextField5.setFocusCycleRoot(true);
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 70, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 160, -1));

        jLabel6.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jLabel6.text")); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jTextField6.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jTextField6.text")); // NOI18N
        jTextField6.setFocusCycleRoot(true);
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 240, -1));

        jLabel7.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jLabel7.text")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jTextField7.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jTextField7.text")); // NOI18N
        jTextField7.setFocusCycleRoot(true);
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 160, -1));

        jLabel8.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jLabel8.text")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jTextField8.setText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jTextField8.text")); // NOI18N
        jTextField8.setFocusCycleRoot(true);
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 720, 170));

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Secuencia", "Cuenta Contable", "Centro de Costo", "Signo", "Monto Banco", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jXTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 720, 240));

        jtoolbmenu.setBackground(new java.awt.Color(255, 255, 255));
        jtoolbmenu.setFloatable(false);
        jtoolbmenu.setAutoscrolls(true);
        jtoolbmenu.setBorderPainted(false);
        jtoolbmenu.setFocusTraversalPolicyProvider(true);
        jtoolbmenu.setInheritsPopupMenu(true);
        jtoolbmenu.setOpaque(false);

        jbtnCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar1.setIcon(new javax.swing.ImageIcon("E:\\sistema_ERP\\ERPSistemaContable\\src\\com\\gps\\erp\\vista\\images\\guardar.png")); // NOI18N
        jbtnCerrar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jbtnCerrar1.toolTipText")); // NOI18N
        jbtnCerrar1.setActionCommand(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jbtnCerrar1.actionCommand")); // NOI18N
        jbtnCerrar1.setFocusable(false);
        jbtnCerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnCerrar1);

        jbtnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-add-icon.png")); // NOI18N
        jbtnNuevo.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jbtnNuevo.toolTipText")); // NOI18N
        jbtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnNuevo);

        jbtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-delete-icon.png")); // NOI18N
        jbtnAceptar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jbtnAceptar.toolTipText")); // NOI18N
        jbtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnAceptar);

        jbtnEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-excel-icon.png")); // NOI18N
        jbtnEditar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jbtnEditar.toolTipText")); // NOI18N
        jbtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnEditar);

        jbtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-conf-icon.png")); // NOI18N
        jbtnCerrar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantenimientoDeAsientoTipo.class, "FrmMantenimientoDeAsientoTipo.jbtnCerrar.toolTipText")); // NOI18N
        jbtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnCerrar);

        getContentPane().add(jtoolbmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed

    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed

    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed

    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarActionPerformed

    }//GEN-LAST:event_jbtnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoDeAsientoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoDeAsientoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoDeAsientoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoDeAsientoTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmMantenimientoDeAsientoTipo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JButton jbtnCerrar1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JToolBar jtoolbmenu;
    // End of variables declaration//GEN-END:variables
}
