/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmMantemientoCorrelativo.java
 *
 * Created on 21-jun-2012, 9:33:09
 */
package com.contab.view;

/**
 *
 * @author cixtic04
 */
public class FrmMantemientoCorrelativo extends javax.swing.JFrame {

    /** Creates new form FrmMantemientoCorrelativo */
    public FrmMantemientoCorrelativo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtoolbmenu = new javax.swing.JToolBar();
        jbtnCerrar = new javax.swing.JButton();
        jbtnCerrar1 = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();
        jbtnAceptar1 = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setTitle(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.title")); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtoolbmenu.setBackground(new java.awt.Color(255, 255, 255));
        jtoolbmenu.setFloatable(false);
        jtoolbmenu.setAutoscrolls(true);
        jtoolbmenu.setBorderPainted(false);
        jtoolbmenu.setFocusTraversalPolicyProvider(true);
        jtoolbmenu.setInheritsPopupMenu(true);
        jtoolbmenu.setOpaque(false);

        jbtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\nuevo.png")); // NOI18N
        jbtnCerrar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jbtnCerrar.toolTipText")); // NOI18N
        jbtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnCerrar);

        jbtnCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar1.setIcon(new javax.swing.ImageIcon("E:\\sistema_ERP\\ERPSistemaContable\\src\\com\\gps\\erp\\vista\\images\\guardar.png")); // NOI18N
        jbtnCerrar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jbtnCerrar1.toolTipText")); // NOI18N
        jbtnCerrar1.setActionCommand(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jbtnCerrar1.actionCommand")); // NOI18N
        jbtnCerrar1.setFocusable(false);
        jbtnCerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnCerrar1);

        jbtnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnNuevo.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\buscar2.png")); // NOI18N
        jbtnNuevo.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jbtnNuevo.toolTipText")); // NOI18N
        jbtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnNuevo);

        jbtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\table-add-icon.png")); // NOI18N
        jbtnAceptar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jbtnAceptar.toolTipText")); // NOI18N
        jbtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnAceptar);

        jbtnAceptar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-delete-icon.png")); // NOI18N
        jbtnAceptar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jbtnAceptar1.toolTipText")); // NOI18N
        jbtnAceptar1.setFocusable(false);
        jbtnAceptar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptar1ActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnAceptar1);

        jbtnEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-excel-icon.png")); // NOI18N
        jbtnEditar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jbtnEditar.toolTipText")); // NOI18N
        jbtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnEditar);

        getContentPane().add(jtoolbmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jPanel1.border.title"))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tabla", "Tipo 1", "Tipo 2", "Correlativo"
            }
        ));
        jScrollPane1.setViewportView(jXTable1);
        jXTable1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jXTable1.columnModel.title0")); // NOI18N
        jXTable1.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jXTable1.columnModel.title1")); // NOI18N
        jXTable1.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jXTable1.columnModel.title2")); // NOI18N
        jXTable1.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jXTable1.columnModel.title3")); // NOI18N

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 590, 257));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 650, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jPanel2.border.title"))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jLabel1.text")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 31, -1, -1));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jLabel2.text")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 63, -1, -1));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jLabel3.text")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jLabel4.text")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jTextField1.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jTextField1.text")); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 160, -1));

        jTextField2.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jTextField2.text")); // NOI18N
        jTextField2.setFocusCycleRoot(true);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 70, -1));

        jTextField3.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jTextField3.text")); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 160, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 160, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jRadioButton1.text")); // NOI18N
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jRadioButton2.text")); // NOI18N
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 110, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jRadioButton3.text")); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText(org.openide.util.NbBundle.getMessage(FrmMantemientoCorrelativo.class, "FrmMantemientoCorrelativo.jRadioButton4.text")); // NOI18N
        jPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 650, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed

    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed

    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed

    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarActionPerformed

    }//GEN-LAST:event_jbtnCerrarActionPerformed

    private void jbtnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAceptar1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantemientoCorrelativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantemientoCorrelativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantemientoCorrelativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantemientoCorrelativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmMantemientoCorrelativo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnAceptar1;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JButton jbtnCerrar1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JToolBar jtoolbmenu;
    // End of variables declaration//GEN-END:variables
}
