/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmSaldoBalanceGeneral.java
 *
 * Created on 23-jun-2012, 10:28:34
 */
package com.contab.view;

/**
 *
 * @author cixtic04
 */
public class FrmSaldoBalanceGeneral extends javax.swing.JFrame {

    /** Creates new form FrmSaldoBalanceGeneral */
    public FrmSaldoBalanceGeneral() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtoolbmenu = new javax.swing.JToolBar();
        jbtnNuevo = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtoolbmenu.setBackground(new java.awt.Color(255, 255, 255));
        jtoolbmenu.setFloatable(false);
        jtoolbmenu.setAutoscrolls(true);
        jtoolbmenu.setBorderPainted(false);
        jtoolbmenu.setFocusTraversalPolicyProvider(true);
        jtoolbmenu.setInheritsPopupMenu(true);
        jtoolbmenu.setOpaque(false);

        jbtnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnNuevo.setIcon(new javax.swing.ImageIcon("E:\\sistema-contable-final\\SistemaERPContable\\src\\com\\contab\\image\\buscar2.png")); // NOI18N
        jbtnNuevo.setToolTipText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jbtnNuevo.toolTipText")); // NOI18N
        jbtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnNuevo);

        jbtnEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-excel-icon.png")); // NOI18N
        jbtnEditar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jbtnEditar.toolTipText")); // NOI18N
        jbtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnEditar);

        getContentPane().add(jtoolbmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jTextField2.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jTextField2.text")); // NOI18N
        jTextField2.setFocusCycleRoot(true);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 160, -1));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jTextField3.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jTextField3.text")); // NOI18N
        jTextField3.setFocusCycleRoot(true);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 70, -1));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jTextField4.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jTextField4.text")); // NOI18N
        jTextField4.setFocusCycleRoot(true);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 70, -1));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, -1));

        jTextField5.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jTextField5.text")); // NOI18N
        jTextField5.setFocusCycleRoot(true);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 70, -1));

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cuenta", "Centro de Costo", "Descripción", "Año", "Dèbito Base Saldo ", "Crédito Base Saldo", "Moneda", "Dèbito Ext  Base Saldo", "Crédito Ext Base Saldo"
            }
        ));
        jXTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jXTable1);
        jXTable1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jXTable1.columnModel.title0")); // NOI18N
        jXTable1.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jXTable1.columnModel.title1")); // NOI18N
        jXTable1.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jXTable1.columnModel.title2")); // NOI18N
        jXTable1.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jXTable1.columnModel.title3")); // NOI18N
        jXTable1.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jXTable1.columnModel.title4")); // NOI18N
        jXTable1.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jXTable1.columnModel.title5")); // NOI18N
        jXTable1.getColumnModel().getColumn(6).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jXTable1.columnModel.title6")); // NOI18N
        jXTable1.getColumnModel().getColumn(7).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jXTable1.columnModel.title7")); // NOI18N
        jXTable1.getColumnModel().getColumn(8).setHeaderValue(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jXTable1.columnModel.title8")); // NOI18N

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 610, 210));

        jLabel6.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jLabel6.text")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jCheckBox1.setText(org.openide.util.NbBundle.getMessage(FrmSaldoBalanceGeneral.class, "FrmSaldoBalanceGeneral.jCheckBox1.text")); // NOI18N
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSaldoBalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSaldoBalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSaldoBalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSaldoBalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmSaldoBalanceGeneral().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JToolBar jtoolbmenu;
    // End of variables declaration//GEN-END:variables
}
