/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmTipoDeCambio.java
 *
 * Created on 21-jun-2012, 10:52:37
 */
package com.contab.view;

/**
 *
 * @author cixtic04
 */
public class FrmTipoDeCambio extends javax.swing.JFrame {

    /** Creates new form FrmTipoDeCambio */
    public FrmTipoDeCambio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtoolbmenu = new javax.swing.JToolBar();
        jbtnCerrar1 = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnAceptar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jxtbTipoCambio = new org.jdesktop.swingx.JXTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtoolbmenu.setBackground(new java.awt.Color(255, 255, 255));
        jtoolbmenu.setFloatable(false);
        jtoolbmenu.setAutoscrolls(true);
        jtoolbmenu.setBorderPainted(false);
        jtoolbmenu.setFocusTraversalPolicyProvider(true);
        jtoolbmenu.setInheritsPopupMenu(true);
        jtoolbmenu.setOpaque(false);

        jbtnCerrar1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\consultar1.png")); // NOI18N
        jbtnCerrar1.setToolTipText(org.openide.util.NbBundle.getMessage(FrmTipoDeCambio.class, "FrmTipoDeCambio.jbtnCerrar1.toolTipText")); // NOI18N
        jbtnCerrar1.setActionCommand(org.openide.util.NbBundle.getMessage(FrmTipoDeCambio.class, "FrmTipoDeCambio.jbtnCerrar1.actionCommand")); // NOI18N
        jbtnCerrar1.setFocusable(false);
        jbtnCerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtoolbmenu.add(jbtnCerrar1);

        jbtnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-add-icon.png")); // NOI18N
        jbtnNuevo.setToolTipText(org.openide.util.NbBundle.getMessage(FrmTipoDeCambio.class, "FrmTipoDeCambio.jbtnNuevo.toolTipText")); // NOI18N
        jbtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnNuevo);

        jbtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAceptar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-delete-icon.png")); // NOI18N
        jbtnAceptar.setToolTipText(org.openide.util.NbBundle.getMessage(FrmTipoDeCambio.class, "FrmTipoDeCambio.jbtnAceptar.toolTipText")); // NOI18N
        jbtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnAceptar);

        jbtnEditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-excel-icon.png")); // NOI18N
        jbtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEditar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnEditar);

        jbtnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cixtic04\\Dropbox\\contabilidad\\src\\img\\table-conf-icon.png")); // NOI18N
        jbtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarActionPerformed(evt);
            }
        });
        jtoolbmenu.add(jbtnCerrar);

        getContentPane().add(jtoolbmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmTipoDeCambio.class, "FrmTipoDeCambio.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 70, -1));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmTipoDeCambio.class, "FrmTipoDeCambio.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 70, -1));

        jxtbTipoCambio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Oficial Tipo Cambio Compra", "Oficial Tipo Cambio Venta", "Paralelo Tipo Cambio Compra", "Paralelo Tipo Cambio Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jxtbTipoCambio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 750, 200));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed

    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed

    }//GEN-LAST:event_jbtnAceptarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed

    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarActionPerformed

    }//GEN-LAST:event_jbtnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTipoDeCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTipoDeCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTipoDeCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTipoDeCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmTipoDeCambio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JButton jbtnCerrar1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JToolBar jtoolbmenu;
    private org.jdesktop.swingx.JXTable jxtbTipoCambio;
    // End of variables declaration//GEN-END:variables
}
